url:
  shortener:
    domain: http://localhost:8765/

spring:
  application:
    name: urlshortener-service
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
