url:
  shortener:
    domain: http://127.0.0.1:8765/

spring:
  application:
    name: urlshortener-service
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
