spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortener_db?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SubsServiceConnectionPool
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
    show-sql: false

kafka:
  statistics:
    topic:
      name: urlshortener-statistics-events
      partitions: 1
      replication-factor: 1

server:
  port: 9090

url:
  shortener:
    domain: https://90af-2401-4900-1c30-4591-651b-801c-b32b-d0fc.ngrok-free.app/