spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortener?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: UrlShortenerServiceConnectionPool
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
    show-sql: false

kafka:
  statistics:
    topic:
      name: urlshortener.statistics.events
      partitions: 1
      replication-factor: 1

server:
  port: 9090

url:
  shortener:
    domain: localhost:8765/