url:
  shortener:
    ui:
      domain: http://localhost:3000

spring:
  application:
    name: urlshortener-service
  jackson:
    default-property-inclusion: non_null
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${spring.application.instance_id:${random.value}}
        register: true
        fail-fast: true
        enabled: true
        prefer-ip-address: true
        catalog-services-watch-delay: 30000
        health-check-interval: 30s
        register-health-check: true
        heartbeat:
          enabled: true
          ttl: 30s
          reregister-service-on-failure: true
        deregister: true
        health-check-critical-timeout: 30s
        health-check-path: null

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      base-path: /admin/management
  endpoint:
    prometheus:
      access: read_only
    health:
      show-details: always
      access: read_only
    info:
      access: read_only

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

statistics:
  service:
    usage:
      base-path: /api/v1/statistics/usage
subscription:
  service:
    active:
      base-path: /api/v1/subscriptions/active