spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27017/urlshortener?authSource=admin
    redis:
      host: 127.0.0.1
      port: 6379
      database: 11
      username:
      password:

kafka:
  statistics:
    topic:
      name: urlshortener.statistics.events
      partitions: 1
      replication-factor: 1

server:
  port: 9090

url:
  shortener:
    domain: localhost:8765/

process:
  node:
    id: ${PROCESS_NODE_ID:1}

statistics:
  service:
    usage:
      base-path: /api/v1/statistics/usage
