url:
  shortener:
    domain: localhost:8765/

spring:
  application:
    name: urlshortener-service
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      access: read_only

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

statistics:
  service:
    usage:
      base-path: /api/v1/statistics/usage
subscription:
  service:
    active:
      base-path: /api/v1/subscriptions/active